# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh_posts',
                'doc_host': 'https://decherd.github.io',
                'git_url': 'https://github.com/decherd/fh_posts',
                'lib_path': 'fh_posts'},
  'syms': {'fh_posts.core': {'fh_posts.core.foo': ('core.html#foo', 'fh_posts/core.py')}}}
